# অধ্যায় ৫ঃ ডেটা প্রিপ্রসেসিং

মেশিন লার্নিং অ্যালগরিদম গুলো ডাটা থেকে শিখে। তাই ডাটা কেমন ভাবে তৈরি করতে হয় যেন মেশিন মেশিন কাটা থেকে খুব ভালোভাবে শিখতে পারে। অধ্যায়ে আমরা জানব কিভাবে মেশিন লার্নিং অ্যালগরিদম জন্য ডাটা প্রস্তুত করতে হয়। এই অধ্যায়ে আমরা যা যা শিখব

১) Rescale data/Normalize data

২) Standardize data

৩) Binarize data

## ৫.১  Rescale data/Normalize data

যখন আমাদের ডাটা সেটে  বিভিন্ন স্কেলের ডাটা থাকে তখন ডাটা সেটটিকে   রিস্কেল  করতে হয় ।  রিস্কেল  করা মানে ডাটা সেটের ডেটাগুলোকে একটি নির্দিষ্ট স্কেলের (0 থেকে ১ ) মধ্যে আনা।  যখন আমাদের ফিচারের ডিস্ট্রিবিউশন গসিয়ান(নরমাল) ডিস্ট্রিবিউশন থাকে না তখন ডেটাকে নরমালাইজ করতে হয়।  এটি অপটিমাইজেশন অ্যালগোরিদমের জন্য খুবই ভালভাবে কাজ করে যেমন গ্রেডিয়েন্ট ডিসেন্ট আলগরিদম।  এছাড়াও নিউরাল নেটওয়ার্ক এবং  k-nearest neighbors এলগোরিদমের জন্য ভালো ভাবে কাজ করে।  আমরা Scikit-learn এর MinMaxScaler  ক্লাস ব্যবহার করে ডেটাকে রিস্কেল করতে পারি।

In [2]:
# Import libraries
import pandas as pd
import numpy as np
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

# load dataset
dataset = pd.read_csv('diabetes.csv')
array = dataset.values
# separate array into input and output components
X = array[:,0:8]
Y = array[:,8]
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)
# summarize transformed data
set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]


## ৫.২ Standardize Data

ডেটাকে Standardize করা মানে হচ্ছে ডেটাগুলোকেগুলোকে এমনভাবে স্কেলিং করতে হবে যে তাদের মিন 0 এবং std 1 হয়। ডেটা Standardize তখন ভালোভাবে কাজ করে যখন ডেটার ডিস্ট্রিবিউশন গসিয়ান ডিস্ট্রিবিউশন হয়। যদি ডেটার গসিয়ান ডিস্ট্রিবিউশন
না হয় তাহলে  ডেটাকে আগে নরমাইলাইজ করে (৫.১ এ আলোচনা করা হয়েছে ) তারপর standardize করতে হবে। গসিয়ান ডিস্ট্রিবিউশন/ডেটা নরমাইলাইজ করা ডেটার সাথে ডেটা Standardize করা থাকলে কিছু মেশিন লার্নিং এলগরিদম (linear regression,logistic regression and linear discriminate analysis) খুব ভালোভাবে কাজ করে। 

আমরা Scikit-learn এর StandardScaler  ক্লাস ব্যবহার করে ডেটাকে Standardize করতে পারি। 

In [3]:
# Standardize data (0 mean, 1 stdev)
from sklearn.preprocessing import StandardScaler
from numpy import set_printoptions
array = dataset.values
# separate array into input and output components
X = array[:,0:8]
Y = array[:,8]
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)
# summarize transformed data
set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


## ৫.৩ Binarize data

In [5]:
from sklearn.preprocessing import Binarizer
array = dataset.values
# separate array into input and output components
X = array[:,0:8]
Y = array[:,8]
binarizer = Binarizer(threshold=0.0).fit(X)
binaryX = binarizer.transform(X)
# summarize transformed data
set_printoptions(precision=3)
print(binaryX[0:5,:])

[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]


# ৫.৪ এই অধ্যায়ে যা যা শিখলাম 

এই অধ্যায়ে আমরা মেশিন লার্নিং এলগরিদমের জন্য ডেটাকে কয়েকটা টেকনিকে তৈরি করা দেখলাম। তবে আরো কিছু টেকনিক ব্যবহার  করে ডেটাকে প্রিপ্রসেস করা যায় তা আমরা সামনে শিখব । 
এই অধ্যায় যে যে টেকনিকগুলো শিখেছি -- 
১) Rescale data/Normalize data

২) Standardize data

৩) Binarize data

# ৫.৫ পরের অধ্যায়ে যা শিখব 

ডেটাকে মেশিন লার্নিং এলগোরিদমের জন্য কিভাবে প্রস্তুত করতে হয়  তা আমরা পারি। সামনের অধ্যায়ে কোন  ফিচারগুলো দরকারি ঐ ফিচারগুলো সিলেক্ট করা শিখব ইনশাআল্লাহ । 